name: run player details script
# Schedule to run the action every 5 minutes
on:
  schedule:
    - cron: "11 */4 * * *" # Run every 15 minutes
# on: [push]

jobs:
  write-time-job:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v4 # Set up Python environment
        with:
          python-version: "3.10" # You can choose the Python version

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python nfl/player_details.py # Run the Python script that writes the current time
